# Generated by Django 5.1.3 on 2024-12-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="object_name",
            field=models.CharField(max_length=255),
        ),
    ]
